services:

  database:
    image: neo4j:5.19.0-enterprise
    environment:
      NEO4J_AUTH: "${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-changeme1234}"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_memory_heap_max__size: "1G"
      NEO4J_dbms_memory_pagecache_size: "2G"
      NEO4J_dbms_connector_http_enabled: "true"
      NEO4J_dbms_connector_http_listen__address: ":${NEO4J_HTTP_PORT:-7474}"
      NEO4J_dbms_connector_http_advertised__address: "localhost:${NEO4J_HTTP_PORT:-7474}"
      NEO4J_dbms_connector_https_enabled: "false"
      NEO4J_dbms_connector_bolt_enabled: "true"
      NEO4J_dbms_connector_bolt_listen__address: ":${NEO4J_BOLT_PORT:-7687}"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:${NEO4J_BOLT_PORT:-7687}"
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${NEO4J_BOLT_PORT:-7687}:7687"
      - "${BIND_ADDRESS:-127.0.0.1}:${NEO4J_HTTP_PORT:-7474}:7474"
    healthcheck:
      test: wget --quiet --spider --timeout 2 --tries 1 http://localhost:${NEO4J_HTTP_PORT:-7474}/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 30s

  api:
    build:
      context: ./clinical_mdr_api
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      NEO4J_DSN: "bolt://${NEO4J_USER:-neo4j}:${NEO4J_PASSWORD:-changeme1234}@database:${NEO4J_BOLT_PORT:-7687}"
      NEO4J_DATABASE: "${NEO4J_DATABASE:-neo4j}"
      OAUTH_ENABLED: "False"
      ALLOW_ORIGIN_REGEX: ".*"
      UVICORN_PORT: "8000"
      UVICORN_PATH:
    ports:
      - "${API_HTTP_PORT:-8000}:8000"
