# Might want to make this file as a template, if we need something similar to our deployment
parameters:
- name: 'NEO4J_MDR_DATABASE'
  displayName: Name of neo4j DB
  type: string
  default: mdrdbdev
- name: 'NEO4J_CDISC_IMPORT_DATABASE'
  displayName: Name of intermediate DB
  type: string
  default: cdisc
- name: 'NEO4J_CDISC_IMPORT_BOLT_PORT'
  displayName: Bolt port of intermediate DB
  type: string
  default: 7687
- name: 'NEO4J_CDISC_IMPORT_HOST'
  displayName: IP address of intermediate DB
  type: string
  default: 10.78.43.90
- name: REPO_REFERENCE
  type: string
  default: self  
- name: 'POOL'
  type: string
  default: false
- name: ID_NUMBER
  displayName: ID number of parallel deployments running in the same environment.
  type: string 
  default: '1'
  values:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
- name: ENV_REFERENCE
  type: string 
  default: DEV
  values:
  - DEV
  - POC
  - EDU
  - VAL
  - TST
  - PRD
- name: 'KEYVAULT_NAME'
  type: string
  default: false

jobs:
- job: import_to_mdr
  pool: ${{parameters.POOL}}
  dependsOn: ct_import
  variables:
    packages: "$[ dependencies.ct_import.outputs['cdiscVar.PACKAGES'] ]"
  timeoutInMinutes: 720
  steps:  
    - checkout: ${{parameters.REPO_REFERENCE}}
    # Specify python version. The version must be manually installed beforehand so the agent has it available.
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.13.0'
        addToPath: true
        architecture: 'x64'

    # Get storage connection specifications from AzureKeyVault
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'clinicalmdr-iac-poc'
        KeyVaultName: '${{parameters.KEYVAULT_NAME}}'
        SecretsFilter: 
          CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-DBUSER,
          CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-DBPASS,
          CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-BOLTPORT,
          CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-SERVER
        RunAsPreJob: false

    # Install packages
    - script: |
        python3 -m venv venv --clear
        source $(Build.SourcesDirectory)/venv/bin/activate
        pip install pipenv
        python -m pipenv install
      displayName: Install packages and prepare
    
    # Load CT and adjust
    - script: |
        source $(Build.SourcesDirectory)/venv/bin/activate
        export NEO4J_MDR_DATABASE=${{parameters.NEO4J_MDR_DATABASE}}
        export NEO4J_MDR_BOLT_PORT=${{parameters.NEO4J_MDR_BOLT_PORT}}
        export NEO4J_MDR_HOST=${{parameters.NEO4J_MDR_HOST}}
        export NEO4J_MDR_AUTH_USER=$(NEO4J-USER)
        export NEO4J_MDR_AUTH_PASSWORD=$(NEO4J-PASS)
        export NEO4J_CDISC_IMPORT_DATABASE=${{parameters.NEO4J_CDISC_IMPORT_DATABASE}}
        export NEO4J_CDISC_IMPORT_BOLT_PORT=${{parameters.NEO4J_CDISC_IMPORT_BOLT_PORT}}
        export NEO4J_CDISC_IMPORT_HOST=${{parameters.NEO4J_CDISC_IMPORT_HOST}}
        export NEO4J_CDISC_IMPORT_AUTH_USER=$(NEO4J-USER)
        export NEO4J_CDISC_IMPORT_AUTH_PASSWORD=$(NEO4J-PASS)

        python -m pipenv run import_from_cdisc_ct_db_into_mdr
      displayName: Import from CDISC CT DB into MDR DB
